import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Blogs from "../components/Blogs";
import Contact from "../components/contact";
import Experience from "../components/Experience";
import HomePage from "../components/home";
import Projects from "../components/Projects";
import Skills from "../components/skills";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col font-montserrat">
      <Head>
        <title>Nayan Patil | Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <HomePage />
      <Skills />
      <Projects />
      <Experience />
      <Blogs />
      <About />
      <Contact />
    </div>
  );
};

export default Home;
